server:
  port: 18081

spring:
  main:
    banner-mode: off
  application:
    name: research-agent-mcp-server
  ai:
    mcp:
      server:
        name: research-agent-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides time information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
    alibaba:
      mcp:
        nacos:
          namespace: 9ba5f1aa-b37d-493b-9057-72918a40ef35
          enabled: true
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          registry:
            enabled: true
            service-group: mcp-server
