server:
  port: 28081

spring:
  main:
    banner-mode: off
    allow-circular-references: true
  application:
    name: research-agent-mcp-server
  ai:
    mcp:
      server:
        name: research-agent-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides time information tools and resources"
        # 配置 sse 的根路径，默认值为 /sse
        sse-endpoint: /sse
        # mcp server nacos注册服务路径，下面的最终路径为 ip:port/sse/mcp/messages
        sse-message-endpoint: /mcp/messages
        # mcp server本地启动服务路径，下面的最终路径为 ip:port/sse/mcp
        #sse-message-endpoint: /mcp
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
    alibaba:
      mcp:
        nacos:
          namespace: public
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          registry:
            enabled: true
            service-group: mcp-server

# 日志配置
logging:
  level:
    root: "info"
    org.springframework.ai: "debug"
    com.alibaba.cloud.api: "debug"
    io.modelcontextprotocol: "debug"
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]" # 设置zipkin和brave配置和tracing的日志信息

