# Compose a postgres database together with the extension pgvector
services:
  pgvector:
    image: pgvector/pgvector:pg17
    ports:
     - 5433:5432
    restart: always
    environment:
      - POSTGRES_DB=researchagent
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    volumes:
      - E:\WorkFiles\docker\pgvector\data:/var/lib/postgresql/data
